In [1]:
from cm_fun import *

In [2]:
# Example usage
A = np.random.rand(8, 5)  # Example matrix with m > n
A

array([[0.67771253, 0.87162677, 0.31288339, 0.07360056, 0.81895444],
       [0.59322524, 0.03661815, 0.48745066, 0.64943238, 0.48323981],
       [0.4497558 , 0.63842537, 0.58401502, 0.16242234, 0.01108902],
       [0.78703291, 0.34106935, 0.91236761, 0.66203742, 0.88534495],
       [0.60599513, 0.68628856, 0.95190746, 0.90166611, 0.69165128],
       [0.11127945, 0.58177615, 0.86745881, 0.96088783, 0.07834453],
       [0.7180819 , 0.00234348, 0.34578048, 0.79383159, 0.5439748 ],
       [0.22636714, 0.50501685, 0.86595572, 0.37773714, 0.43020761]])

In [3]:
U = np.random.rand(8, 2) 
U

array([[0.58183641, 0.90781939],
       [0.02856209, 0.35321544],
       [0.32227026, 0.39517582],
       [0.35120805, 0.11057241],
       [0.80430845, 0.45832219],
       [0.08278897, 0.54920751],
       [0.92423952, 0.79262696],
       [0.37149861, 0.46479284]])

In [4]:
V = np.random.rand(5, 2)
V

array([[0.15247776, 0.01570102],
       [0.18893613, 0.30147292],
       [0.41268406, 0.49501846],
       [0.60333523, 0.76516108],
       [0.22822939, 0.34532534]])

In [5]:
print('Prima Fun:', objective_function(A,U,V))

Prima Fun: 2.7445565528331577


In [6]:
V_r, householder_vectors = thin_qr_factorization(V)
AQ = apply_householder_transformations(A, householder_vectors)
U_1 = backward_substitution(AQ, np.transpose(V_r))

In [7]:
print('Seconda Fun:', objective_function(A,U_1,V))

Seconda Fun: 1.919365634227163


In [8]:
U_r, householder_vectors = thin_qr_factorization(U_1)
AQ = apply_householder_transformations(np.transpose(A), householder_vectors)
V_1 = backward_substitution(AQ, np.transpose(U_r))

In [9]:
V_1

array([[0.22189987, 0.06204039],
       [0.39382118, 0.64563777],
       [0.52890632, 0.74646056],
       [0.42212514, 0.51381023],
       [0.28112285, 0.23925567]])

In [10]:
print('Terza Fun:', objective_function(A,U_1,V_1))

Terza Fun: 1.3553212464624775
