In [1]:
from cm_fun import *

In [2]:
# Example usage
A = np.random.rand(8, 5)  # Example matrix with m > n
A

array([[0.088209  , 0.98819417, 0.15654336, 0.43883233, 0.16486376],
       [0.25486439, 0.95108355, 0.42509123, 0.30730772, 0.4083842 ],
       [0.05270978, 0.37983852, 0.95478353, 0.55774952, 0.17051149],
       [0.05742173, 0.81986828, 0.69581406, 0.79563512, 0.22941544],
       [0.16469774, 0.89438052, 0.46703308, 0.63481603, 0.69447265],
       [0.43024776, 0.35778135, 0.19211752, 0.45442294, 0.72626675],
       [0.10442711, 0.75178417, 0.20942144, 0.86536086, 0.08143518],
       [0.24637995, 0.65492694, 0.98865536, 0.8307066 , 0.62433527]])

In [3]:
U = np.random.rand(8, 2) 
U

array([[0.82194018, 0.31039035],
       [0.84495233, 0.13362156],
       [0.03606992, 0.12228525],
       [0.04769946, 0.10324368],
       [0.38100863, 0.91088082],
       [0.46410065, 0.19806846],
       [0.83725103, 0.90776615],
       [0.49963863, 0.04046609]])

In [4]:
V = np.random.rand(5, 2)
V

array([[0.28628656, 0.52809182],
       [0.42071456, 0.82101944],
       [0.53091812, 0.07116019],
       [0.51185901, 0.14600502],
       [0.21983804, 0.60876303]])

In [5]:
print('Prima Fun:', objective_function(A,U,V))

Prima Fun: 2.536912431828749


In [6]:
V_r, householder_vectors = thin_qr_factorization(V)
AQ = apply_householder_transformations(A, householder_vectors)
U_t = backward_substitution(AQ, np.transpose(V_r))

U_r, householder_vectors = thin_qr_factorization(U_t)
AQ = apply_householder_transformations(np.transpose(A), householder_vectors)
V_t = backward_substitution(AQ, np.transpose(U_r))

In [7]:
print('Seconda Fun:', objective_function(A,U_t,V_t))

Seconda Fun: 0.9915458299250735


In [74]:
V_r, householder_vectors = thin_qr_factorization(V_t)
AQ = apply_householder_transformations(A, householder_vectors)
U_t = backward_substitution(AQ, np.transpose(V_r))

U_r, householder_vectors = thin_qr_factorization(U_t)
AQ = apply_householder_transformations(np.transpose(A), householder_vectors)
V_t = backward_substitution(AQ, np.transpose(U_r))

print('Fun:', objective_function(A,U_t,V_t))

Fun: 0.9476336414541195
