In [1]:
import pandas as pd
import numpy as np
from plot_utils import *
from math_utils import *
from off_the_shelf_utils import *
from pathlib import Path

# Specifica la cartella
horse_path = Path('./data/img/horse')


In [2]:
#img_A = load_image_as_grayscale_matrix('./data/img/mnist/0/101.png')
#img_A = resize_image(img_A, 100, 100)

img_A = np.dot(np.random.rand(6, 2), np.random.rand(5,2).transpose())
img_A

array([[1.3295288 , 0.78602133, 1.31873487, 0.85158193, 1.07081619],
       [0.81651398, 0.44668013, 0.82737074, 0.50527422, 0.79337161],
       [0.80789801, 0.44948445, 0.81499333, 0.5036371 , 0.75668882],
       [0.63497438, 0.36217622, 0.63623355, 0.40021184, 0.56120943],
       [0.87097062, 0.55933444, 0.84235413, 0.57969626, 0.5342302 ],
       [0.63282972, 0.29765549, 0.66479046, 0.36775254, 0.79768529]])

In [3]:
methods = [
    'rand_u',           # Uniform Distribution
    'rand_n',           # Normal Distribution
    'scaled_u',         # Scaled Uniform Distribution
    'scaled_n',         # Scaled Normal Distribution
    'sketching_g',      # Sketching with Gaussian Distribution
    'sketching_b',      # Sketching with Bernoulli Distribution
    'semi-orthogonal'   # Semi-Orthogonal via Householder
]
epsilon = [
    1e-08,
    np.finfo(np.float64).eps
]
ks = [
    1,
    2,
    5,
    10,
    20,
    50,
    100,
    200
]

In [4]:
start(img_A, 3, 'pretest', 'low_rank_6x5',  f'test_non_convergenza', 'sketching_g', epsilon=epsilon[0])

V_r [[ 7.07351588e-01  2.01997311e+00  1.33704213e+00]
 [ 0.00000000e+00 -7.27632747e-01 -3.07088116e-01]
 [ 0.00000000e+00  0.00000000e+00  1.30369980e-16]]
AQ [[-2.39858022e+00  4.93143020e-01 -1.49205303e-16]
 [-1.49623596e+00  4.43597864e-01  8.45742932e-17]
 [-1.47561359e+00  4.09563689e-01 -5.04121878e-17]
 [-1.15404847e+00  2.87149577e-01 -7.51566317e-17]
 [-1.54274516e+00  1.49640682e-01 -9.50075848e-17]
 [-1.19085064e+00  5.33326461e-01  7.38640115e-17]]
U_t [[-3.39093071  0.          0.        ]
 [-2.11526486  0.          0.        ]
 [-2.08611052  0.          0.        ]
 [-1.63150615  0.          0.        ]
 [-2.18101604  0.          0.        ]
 [-1.68353427  0.          0.        ]]
low_rank_6x5 | test_non_convergenza | 0 | 0.002s | obj=0.99849679359020360 | U=5.52969660420720377 | V=2.64425260461330192 |


c:\Users\cicci\Desktop\uni\CM\CM_Project\math_utils.py:38: RuntimeWarning: invalid value encountered in divide
  vk /= np.linalg.norm(vk)


U_r [[5.5296966 0.        0.       ]
 [0.              nan       nan]
 [0.        0.              nan]]
AQ [[-2.15595986         nan         nan]
 [-1.24053609         nan         nan]
 [-2.15498574         nan         nan]
 [-1.36417714         nan         nan]
 [-1.86475021         nan         nan]]
V_t [[nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]]
low_rank_6x5 | test_non_convergenza | 0 | 0.003s | obj=nan | U=5.52969660420720377 | V=nan |


KeyboardInterrupt: Interrupted by user

In [5]:
for meth in methods[5:]:
    for k in ks:
        #start(img_A, k, 'mnist_500', '0_212',  f'{k}_{meth}_{epsilon[0]}', meth, epsilon=epsilon[0])
        continue

In [ ]:
thin_qr_factorization(np.array([[]]))